### ISSUE TITLE
samplot errors out when trying to generate png

### ISSUE THREAD

**Issue by rsolano1-uw** [ryanlayer/samplot#119]
Versions:
**OS**: CentOS 7
**samplot**: 1.0.1
**Python**: 3.7.7
**numpy**: 1.19.2
**matplotlib**: 3.2.1
**pysam**: 0.16.0.1

Error Output:
```
Traceback (most recent call last):
  File "/path/to/samplot", line 152, in get_tabix_iter
    itr = tbx.fetch(chrm, max(0, start-1000), end+1000)
  File "pysam/libctabix.pyx", line 509, in pysam.libctabix.TabixFile.fetch
ValueError: could not create iterator for region '6:79785917-79789285'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/samplot", line 161, in get_tabix_iter
    itr = tbx.fetch(chrm, max(0,start-1000), end+1000)
  File "pysam/libctabix.pyx", line 509, in pysam.libctabix.TabixFile.fetch
ValueError: could not create iterator for region '6:79785917-79789285'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/samplot", line 3207, in <module>
    current_axis_idx)
  File "/path/to/samplot", line 2830, in plot_annotations
    annotation_plan = get_plot_annotation_plan(ranges, annotation_file)
  File "/path/to/samplot", line 2786, in get_plot_annotation_plan
    itr = get_tabix_iter(r.chrm, r.start, r.end, annotation_file)
  File "/path/to/samplot", line 165, in get_tabix_iter
    ' from ' + datafile)
TypeError: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/path/to/samplot", line 152, in get_tabix_iter
    itr = tbx.fetch(chrm, max(0, start-1000), end+1000)
  File "pysam/libctabix.pyx", line 509, in pysam.libctabix.TabixFile.fetch
ValueError: could not create iterator for region '7:70250695-70599526'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/samplot", line 161, in get_tabix_iter
    itr = tbx.fetch(chrm, max(0,start-1000), end+1000)
  File "pysam/libctabix.pyx", line 509, in pysam.libctabix.TabixFile.fetch
ValueError: could not create iterator for region '7:70250695-70599526'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/samplot", line 3207, in <module>
    current_axis_idx)
  File "/path/to/samplot", line 2830, in plot_annotations
    annotation_plan = get_plot_annotation_plan(ranges, annotation_file)
  File "/path/to/samplot", line 2786, in get_plot_annotation_plan
    itr = get_tabix_iter(r.chrm, r.start, r.end, annotation_file)
  File "/path/to/samplot", line 165, in get_tabix_iter
    ' from ' + datafile)
TypeError: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/path/to/samplot", line 152, in get_tabix_iter
    itr = tbx.fetch(chrm, max(0, start-1000), end+1000)
  File "pysam/libctabix.pyx", line 509, in pysam.libctabix.TabixFile.fetch
ValueError: could not create iterator for region '9:95278469-96418357'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/samplot", line 161, in get_tabix_iter
    itr = tbx.fetch(chrm, max(0,start-1000), end+1000)
  File "pysam/libctabix.pyx", line 509, in pysam.libctabix.TabixFile.fetch
ValueError: could not create iterator for region '9:95278469-96418357'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/samplot", line 3207, in <module>
    current_axis_idx)
  File "/path/to/samplot", line 2830, in plot_annotations
    annotation_plan = get_plot_annotation_plan(ranges, annotation_file)
  File "/path/to/samplot", line 2786, in get_plot_annotation_plan
    itr = get_tabix_iter(r.chrm, r.start, r.end, annotation_file)
  File "/path/to/samplot", line 165, in get_tabix_iter
    ' from ' + datafile)
TypeError: can only concatenate str (not "int") to str

```

Command run:
`samplot -b 430477.merged.matefixed.sorted.markeddups.recal.bam 430478.merged.matefixed.sorted.markeddups.recal.bam 430479.merged.matefixed.sorted.markeddups.recal.bam -o 5_79786916_79788285.png -c 5 -s 79786916 -e 79788285 -T Homo_sapiens.GRCh37.82.sort.gff3.gz -A wgEncodeDukeMapabilityUniqueness35bp.bed.gz`

Expected Output:
A PNG is generated

Troubleshooting steps:
I really don't know what this error means. I built and used the most recent version from the master branch (Commited 09/04/2020), and the behavior for that is different (runs and exits 0 but does not generate a png). I am using a hand-built samplot installation instead of a conda-installed samplot.

Any help would be greatly appreciated.

**Comment by jbelyeu** [comment]
I'm a bit confusing with versioning here. Line numbers in the error message you shared don't match the current versions (1.0.18 or higher). Can you double-check, maybe checkout again? This issue looks similar to one we fixed some time ago so I'm optimistic that an update will solve your problem.

**Comment by rsolano1-uw** [comment]
I'm not certain what you mean by "1.0.18 or higher". The github [releases page](https://github.com/ryanlayer/samplot/releases/) for samplot only has version 1.0.1. Do you want me to use the latest git commit? When I try that, a png is still not generated, but no errors show up.

**Comment by jbelyeu** [comment]
Got it. Yeah, the releases page is not up to date as we expect users to either install from conda or clone the repo and build from scratch (notice that the date on the 1.0.1 release is last June). I'll update that, tho, as it's a reasonable option for install. Notice that the current version of samplot has a modified version of the run command (documented in the readme).

**Comment by rsolano1-uw** [comment]
Thank you for updating the releases page. I downloaded the updated release for 1.0.18 and ran the same command with `samplot plot ` instead of `samplot` and it generated some PNGs. Thank you

**Comment by jbelyeu** [comment]
Awesome, glad to be of assistance
